# Generated by Django 5.2.5 on 2026-03-10 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodoffer',
            name='quantity_sold',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='foodoffer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RESERVED', 'Reserved'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('SOLD_OUT', 'Sold Out')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
