# Generated by Django 5.2.5 on 2026-02-27 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.CharField(default='fa-store', help_text='Icône FontAwesome ou classe CSS', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name="Image d'illustration")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de partenaire',
                'verbose_name_plural': 'Catégories de partenaires',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires/logos/', verbose_name='Logo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='partenaires/covers/', verbose_name='Image de couverture')),
                ('address', models.CharField(max_length=300, verbose_name='Adresse')),
                ('city', models.CharField(default='Lomé', max_length=100, verbose_name='Ville')),
                ('quarter', models.CharField(db_index=True, max_length=100, verbose_name='Quartier')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=20)),
                ('opening_time', models.TimeField(verbose_name="Heure d'ouverture")),
                ('closing_time', models.TimeField(verbose_name='Heure de fermeture')),
                ('working_days', models.JSONField(default=list, help_text="Liste des jours d'ouverture (ex: ['monday', 'tuesday', 'wednesday'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='partners.categorypartner', verbose_name='Catégorie')),
                ('owner', models.OneToOneField(limit_choices_to={'role': 'PARTNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'partner',
                'verbose_name_plural': 'partners',
                'indexes': [models.Index(fields=['status', 'quarter'], name='partners_pa_status_4e1724_idx'), models.Index(fields=['category', 'status'], name='partners_pa_categor_443229_idx')],
            },
        ),
    ]
