# Generated by Django 5.2.5 on 2026-02-27 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'PARTNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['owner', 'status'], name='partners_pa_owner_i_7130f0_idx'),
        ),
    ]
