"""
Django settings for GastivaAPI project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from decouple import config
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--xj*44vo@4rs&#74#cr@&r(%47qmrx03ge!)_0o*m-s@1$&f2-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_spectacular',
    'django_filters',
    
    # Your apps
    #'apps.core',
    'apps.accounts',
    'apps.partners',
    'apps.offers',
    'apps.orders',
    'apps.payments',
    'apps.reviews',
    'apps.notifications',
    'apps.dashboard',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Backend par défaut
    'apps.accounts.backends.PhoneOrEmailBackend', 
]

AUTH_USER_MODEL = 'accounts.User'

# DRF Settings améliorées
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
}

# Spectacular (Swagger) Settings améliorés
SPECTACULAR_SETTINGS = {
    'TITLE': 'Anti-Gaspillage Alimentaire API',
    'DESCRIPTION': """
    API REST pour l'application anti-gaspillage alimentaire.
    
    ## Fonctionnalités principales
    * Gestion des utilisateurs (inscription/connexion avec téléphone ou email)
    * Gestion des restaurants et de leurs offres
    * Système de commandes
    * Paiements Mobile Money (T-Money, Floz)
    * Avis et notations
    * Notifications
    
    ## Authentification
    Cette API utilise JWT (JSON Web Tokens) pour l'authentification.
    * Obtenez un token via `/api/accounts/login/`
    * Utilisez le token dans le header: `Authorization: Bearer <votre_token>`
    """,
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
    },
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_NO_READ_ONLY_REQUIRED': True,
    'TAGS': [
        {'name': 'accounts', 'description': 'Gestion des utilisateurs et authentification'},
        {'name': 'restaurants', 'description': 'Gestion des restaurants'},
        {'name': 'offers', 'description': 'Gestion des offres alimentaires'},
        {'name': 'orders', 'description': 'Gestion des commandes'},
        {'name': 'payments', 'description': 'Gestion des paiements'},
        {'name': 'reviews', 'description': 'Avis et notations'},
        {'name': 'notifications', 'description': 'Notifications'},
    ],

    'ENUM_NAME_OVERRIDES': {
        'OrderStatus': 'apps.orders.models.Order.Status',
        'OfferStatus': 'apps.offers.models.FoodOffer.Status',
        'PartnerStatus': 'apps.partners.models.Partner.Status',
        'PaymentStatus': 'apps.payments.models.Payment.Status',
        'PaymentMethod': 'apps.payments.models.Payment.PaymentMethod',
        'UserRole': 'apps.accounts.models.User.Role',
        'NotificationType': 'apps.notifications.models.Notification.NotificationType',
        'NotificationPriority': 'apps.notifications.models.Notification.Priority',
    },
    
}

CORS_ALLOW_ALL_ORIGINS = True 

# Simple JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'phone_number',  # Utiliser phone_number comme identifiant
    'USER_ID_CLAIM': 'phone_number',
}

ROOT_URLCONF = 'GastivaAPI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GastivaAPI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files configuration
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
