# Generated by Django 5.2.5 on 2026-02-27 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, help_text='Format de numéro togolais', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone togolais valide requis (8 chiffres commençant par 90,91,92,93,70,71,79)', regex='^(90|91|92|93|70|71|79|78|99|98|96|97)\\d{6}$')]),
        ),
    ]
