# Generated by Django 5.2.5 on 2026-03-05 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, help_text='Format de numéro togolais', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone togolais valide requis (8 chiffres commençant par 90,91,92,93,70,71,79)', regex='^(90|91|92|93|70|71|79|78|99|98|96|97)\\d{6}$')]),
        ),
    ]
