# Generated by Django 5.2.5 on 2026-02-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='partner',
        ),
    ]
