# Generated by Django 5.2.5 on 2026-03-07 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_push', models.BooleanField(default=True)),
                ('allow_email', models.BooleanField(default=True)),
                ('allow_sms', models.BooleanField(default=False)),
                ('allow_in_app', models.BooleanField(default=True)),
                ('type_preferences', models.JSONField(blank=True, default=dict)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'préférence de notification',
                'verbose_name_plural': 'préférences de notification',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER_CREATED', 'Commande créée'), ('ORDER_CONFIRMED', 'Commande confirmée'), ('ORDER_READY', 'Commande prête'), ('ORDER_PICKED_UP', 'Commande retirée'), ('ORDER_CANCELLED', 'Commande annulée'), ('PAYMENT_SUCCESS', 'Paiement réussi'), ('PAYMENT_FAILED', 'Paiement échoué'), ('PAYMENT_REFUNDED', 'Remboursement effectué'), ('OFFER_NEAR_EXPIRY', 'Offre bientôt expirée'), ('OFFER_NEW', 'Nouvelle offre'), ('OFFER_POPULAR', 'Offre populaire'), ('PICKUP_REMINDER', 'Rappel de retrait'), ('REVIEW_REMINDER', "Rappel d'avis"), ('WELCOME', 'Bienvenue'), ('ACCOUNT_VERIFIED', 'Compte vérifié'), ('PARTNER_APPROVED', 'Partenaire approuvé'), ('PARTNER_SUSPENDED', 'Partenaire suspendu')], db_index=True, max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('URGENT', 'Urgente')], db_index=True, default='MEDIUM', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/')),
                ('icon', models.CharField(default='notifications', max_length=50)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent_push', models.BooleanField(default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent_email', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent_sms', models.BooleanField(default=False)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['notification_type', 'priority'], name='notificatio_notific_b9c0e7_idx'), models.Index(fields=['expires_at'], name='notificatio_expires_4f3289_idx')],
            },
        ),
    ]
